"""Lark-CLI business adapter.

This module classifies available Lark CLI tool families by business domain and
builds intent-level call plans. It does not execute tools directly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
import subprocess
from typing import Any

from app.domain.capability_registry import get_capability_spec, normalize_payload
from app.domain.enums import CapabilityId, IntentType


class BusinessDomain(StrEnum):
    """Business domains used for adapter routing."""

    MESSAGE = "message"
    CALENDAR = "calendar"
    DOC_SHEET = "doc_sheet"
    CONTACT = "contact"
    TASK = "task"
    MAIL = "mail"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class CliInvocation:
    """A normalized invocation unit for downstream executor/service."""

    tool_family: str
    operation: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CliCallPlan:
    """Intent-to-business call plan generated by adapter."""

    capability_id: CapabilityId
    domain: BusinessDomain
    invocations: tuple[CliInvocation, ...]
    intent: IntentType = IntentType.UNKNOWN


class LarkCliAdapter:
    """Build business-level CLI plans from normalized intents."""

    def build_plan_for_capability(
        self,
        capability_id: CapabilityId,
        payload: dict[str, Any],
        intent: IntentType = IntentType.UNKNOWN,
    ) -> CliCallPlan:
        """Create a CLI plan from a normalized capability action."""
        spec = get_capability_spec(capability_id)
        if spec is not None:
            domain = self._domain_for_capability(capability_id)
            return CliCallPlan(
                intent=intent,
                capability_id=capability_id,
                domain=domain,
                invocations=(
                    CliInvocation(
                        tool_family=spec.cli_tool_family,
                        operation=spec.cli_operation,
                        arguments=normalize_payload(capability_id, payload),
                    ),
                ),
            )
        return CliCallPlan(
            intent=intent,
            capability_id=CapabilityId.UNKNOWN,
            domain=BusinessDomain.UNKNOWN,
            invocations=tuple(),
        )

    @staticmethod
    def _domain_for_capability(capability_id: CapabilityId) -> BusinessDomain:
        if capability_id.value.startswith("im."):
            return BusinessDomain.MESSAGE
        if capability_id.value.startswith("calendar."):
            return BusinessDomain.CALENDAR
        if capability_id.value.startswith(("docs.", "sheets.", "base.")):
            return BusinessDomain.DOC_SHEET
        if capability_id.value.startswith("contact."):
            return BusinessDomain.CONTACT
        if capability_id.value.startswith("task."):
            return BusinessDomain.TASK
        if capability_id.value.startswith("mail."):
            return BusinessDomain.MAIL
        return BusinessDomain.UNKNOWN

    def build_command(
        self,
        invocation: CliInvocation,
        cli_bin: str = "lark-cli",
        dry_run: bool = False,
    ) -> list[str]:
        """Convert one invocation into a concrete lark-cli command argv."""
        if invocation.tool_family == "lark-im" and invocation.operation == "message_send":
            return self._build_im_message_send(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-im" and invocation.operation == "messages_search":
            return self._build_im_messages_search(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-im" and invocation.operation == "messages_reply":
            return self._build_im_messages_reply(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-im" and invocation.operation == "chat_messages_list":
            return self._build_im_chat_messages_list(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-im" and invocation.operation == "chat_search":
            return self._build_im_chat_search(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-im" and invocation.operation == "chat_create":
            return self._build_im_chat_create(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-doc" and invocation.operation == "doc_create":
            return self._build_doc_create(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-doc" and invocation.operation == "doc_update":
            return self._build_doc_update(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-doc" and invocation.operation == "doc_search":
            return self._build_doc_search(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-calendar" and invocation.operation == "calendar_create":
            return self._build_calendar_create(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-calendar" and invocation.operation == "agenda":
            return self._build_calendar_agenda(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        if invocation.tool_family == "lark-calendar" and invocation.operation == "freebusy":
            return self._build_calendar_freebusy(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        raise ValueError(
            f"unsupported cli invocation: tool={invocation.tool_family}, operation={invocation.operation}"
        )

    @staticmethod
    def stringify_command(argv: list[str]) -> str:
        """Render command for logs/docs in Windows-compatible format."""
        return subprocess.list2cmdline(argv)

    @staticmethod
    def _build_im_message_send(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        text = str(arguments.get("text", "")).strip()
        if not text:
            raise ValueError("missing message text for lark-im +messages-send")
        chat_id = str(arguments.get("chat_id", "")).strip()
        user_id = str(arguments.get("user_id", "")).strip()
        if not chat_id and not user_id:
            raise ValueError("missing chat_id/user_id for lark-im +messages-send")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "im", "+messages-send", "--as", identity, "--text", text]
        if chat_id:
            command.extend(["--chat-id", chat_id])
        else:
            command.extend(["--user-id", user_id])
        idempotency_key = str(arguments.get("idempotency_key", "")).strip()
        if idempotency_key:
            command.extend(["--idempotency-key", idempotency_key])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_im_messages_search(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        query = str(arguments.get("query", "")).strip()
        if not query:
            raise ValueError("missing query for lark-im +messages-search")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity != "user":
            raise ValueError("lark-im +messages-search requires user identity")
        command = [cli_bin, "im", "+messages-search", "--as", identity, "--query", query]
        chat_id = str(arguments.get("chat_id", "")).strip()
        if chat_id:
            command.extend(["--chat-id", chat_id])
        start_time = str(arguments.get("start_time", "")).strip()
        if start_time:
            command.extend(["--start-time", start_time])
        end_time = str(arguments.get("end_time", "")).strip()
        if end_time:
            command.extend(["--end-time", end_time])
        limit = arguments.get("limit")
        if isinstance(limit, int) and limit > 0:
            command.extend(["--page-limit", str(limit)])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_im_messages_reply(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        text = str(arguments.get("text", "")).strip()
        if not text:
            raise ValueError("missing text for lark-im +messages-reply")
        message_id = str(arguments.get("message_id", "")).strip()
        thread_id = str(arguments.get("thread_id", "")).strip()
        if not message_id and not thread_id:
            raise ValueError("missing message_id/thread_id for lark-im +messages-reply")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "im", "+messages-reply", "--as", identity, "--text", text]
        if message_id:
            command.extend(["--message-id", message_id])
        if thread_id:
            command.extend(["--thread-id", thread_id])
        if bool(arguments.get("reply_in_thread", False)):
            command.append("--reply-in-thread")
        idempotency_key = str(arguments.get("idempotency_key", "")).strip()
        if idempotency_key:
            command.extend(["--idempotency-key", idempotency_key])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_im_chat_messages_list(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        chat_id = str(arguments.get("chat_id", "")).strip()
        user_id = str(arguments.get("user_id", "")).strip()
        if not chat_id and not user_id:
            raise ValueError("missing chat_id/user_id for lark-im +chat-messages-list")
        if chat_id and user_id:
            raise ValueError("chat_id and user_id cannot both be set for lark-im +chat-messages-list")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        if user_id and identity != "user":
            raise ValueError("lark-im +chat-messages-list with user_id requires user identity")
        command = [cli_bin, "im", "+chat-messages-list", "--as", identity]
        if chat_id:
            command.extend(["--chat-id", chat_id])
        else:
            command.extend(["--user-id", user_id])
        start_time = str(arguments.get("start_time", "")).strip()
        if start_time:
            command.extend(["--start", start_time])
        end_time = str(arguments.get("end_time", "")).strip()
        if end_time:
            command.extend(["--end", end_time])
        limit = arguments.get("limit")
        if isinstance(limit, int) and limit > 0:
            command.extend(["--page-size", str(limit)])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_im_chat_search(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        query = str(arguments.get("query", "")).strip()
        if not query:
            raise ValueError("missing query for lark-im +chat-search")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "im", "+chat-search", "--as", identity, "--query", query]
        limit = arguments.get("limit")
        if isinstance(limit, int) and limit > 0:
            command.extend(["--page-size", str(limit)])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_im_chat_create(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        name = str(arguments.get("name", "")).strip()
        if not name:
            raise ValueError("missing name for lark-im +chat-create")
        identity = str(arguments.get("identity", "bot")).strip().lower() or "bot"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "im", "+chat-create", "--as", identity, "--name", name]
        description = str(arguments.get("description", "")).strip()
        if description:
            command.extend(["--description", description])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_doc_create(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        title = str(arguments.get("title", "")).strip()
        if not title:
            raise ValueError("missing title for lark-cli docs +create")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "docs", "+create", "--as", identity, "--title", title]
        markdown = str(arguments.get("content", "")).strip()
        if markdown:
            command.extend(["--markdown", markdown])
        folder_token = str(arguments.get("folder_token", "")).strip()
        if folder_token:
            command.extend(["--folder-token", folder_token])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_doc_update(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        doc_token = str(arguments.get("doc_token", "")).strip()
        if not doc_token:
            raise ValueError("missing doc_token for lark-cli docs +update")
        markdown = str(arguments.get("content", "")).strip()
        if not markdown:
            raise ValueError("missing content for lark-cli docs +update")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [
            cli_bin,
            "docs",
            "+update",
            "--as",
            identity,
            "--doc",
            doc_token,
            "--mode",
            "append",
            "--markdown",
            markdown,
        ]
        new_title = str(arguments.get("title", "")).strip()
        if new_title:
            command.extend(["--new-title", new_title])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_doc_search(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        query = str(arguments.get("query", "")).strip()
        if not query:
            raise ValueError("missing query for lark-cli docs +search")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity != "user":
            raise ValueError("lark-cli docs +search requires user identity")
        command = [cli_bin, "docs", "+search", "--as", identity, "--query", query]
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_calendar_create(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        title = str(arguments.get("title", "")).strip()
        start_time = str(arguments.get("start_time", "")).strip()
        end_time = str(arguments.get("end_time", "")).strip()
        if not title:
            raise ValueError("missing title for lark-cli calendar +create")
        if not start_time:
            raise ValueError("missing start_time for lark-cli calendar +create")
        if not end_time:
            raise ValueError("missing end_time for lark-cli calendar +create")
        identity = LarkCliAdapter._identity(arguments, default="user")
        command = [
            cli_bin,
            "calendar",
            "+create",
            "--as",
            identity,
            "--summary",
            title,
            "--start",
            start_time,
            "--end",
            end_time,
        ]
        attendee_ids = LarkCliAdapter._join_ids(arguments.get("attendee_ids"))
        if attendee_ids:
            command.extend(["--attendee-ids", attendee_ids])
        calendar_id = str(arguments.get("calendar_id", "")).strip()
        if calendar_id:
            command.extend(["--calendar-id", calendar_id])
        description = str(arguments.get("description", "")).strip()
        if description:
            command.extend(["--description", description])
        rrule = str(arguments.get("rrule", "")).strip()
        if rrule:
            command.extend(["--rrule", rrule])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_calendar_agenda(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        identity = LarkCliAdapter._identity(arguments, default="user")
        command = [cli_bin, "calendar", "+agenda", "--as", identity]
        start_time = str(arguments.get("start_time", "")).strip()
        if start_time:
            command.extend(["--start", start_time])
        end_time = str(arguments.get("end_time", "")).strip()
        if end_time:
            command.extend(["--end", end_time])
        calendar_id = str(arguments.get("calendar_id", "")).strip()
        if calendar_id:
            command.extend(["--calendar-id", calendar_id])
        output_format = str(arguments.get("format", "")).strip()
        if output_format:
            command.extend(["--format", output_format])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _build_calendar_freebusy(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        identity = LarkCliAdapter._identity(arguments, default="user")
        command = [cli_bin, "calendar", "+freebusy", "--as", identity]
        start_time = str(arguments.get("start_time", "")).strip()
        if start_time:
            command.extend(["--start", start_time])
        end_time = str(arguments.get("end_time", "")).strip()
        if end_time:
            command.extend(["--end", end_time])
        user_id = str(arguments.get("user_id", "")).strip()
        if user_id:
            command.extend(["--user-id", user_id])
        output_format = str(arguments.get("format", "")).strip()
        if output_format:
            command.extend(["--format", output_format])
        if dry_run:
            command.append("--dry-run")
        return command

    @staticmethod
    def _identity(arguments: dict[str, Any], default: str) -> str:
        identity = str(arguments.get("identity", default)).strip().lower() or default
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        return identity

    @staticmethod
    def _join_ids(value: Any) -> str:
        if isinstance(value, list):
            return ",".join(str(item).strip() for item in value if str(item).strip())
        return str(value or "").strip()
