"""Lark-CLI business adapter.

This module classifies available Lark CLI tool families by business domain and
builds intent-level call plans. It does not execute tools directly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
import subprocess
from typing import Any

from app.domain.enums import CapabilityId, IntentType


class BusinessDomain(StrEnum):
    """Business domains used for adapter routing."""

    MESSAGE = "message"
    CALENDAR = "calendar"
    DOC_SHEET = "doc_sheet"
    CONTACT = "contact"
    TASK = "task"
    MAIL = "mail"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class CliToolFamily:
    """One Lark CLI tool family grouped by business semantics."""

    tool_name: str
    domain: BusinessDomain
    capabilities: tuple[str, ...]


@dataclass(frozen=True)
class CliInvocation:
    """A normalized invocation unit for downstream executor/service."""

    tool_family: str
    operation: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CliCallPlan:
    """Intent-to-business call plan generated by adapter."""

    capability_id: CapabilityId
    domain: BusinessDomain
    invocations: tuple[CliInvocation, ...]
    fallback_hint: str
    intent: IntentType = IntentType.UNKNOWN


TOOL_FAMILIES: tuple[CliToolFamily, ...] = (
    CliToolFamily(
        tool_name="lark-im",
        domain=BusinessDomain.MESSAGE,
        capabilities=("message_send", "message_reply", "chat_history_search"),
    ),
    CliToolFamily(
        tool_name="lark-calendar",
        domain=BusinessDomain.CALENDAR,
        capabilities=("event_create", "event_reschedule", "freebusy_query"),
    ),
    CliToolFamily(
        tool_name="lark-doc",
        domain=BusinessDomain.DOC_SHEET,
        capabilities=("doc_create", "doc_update", "doc_search"),
    ),
    CliToolFamily(
        tool_name="lark-sheets",
        domain=BusinessDomain.DOC_SHEET,
        capabilities=("sheet_read", "sheet_write", "sheet_append"),
    ),
    CliToolFamily(
        tool_name="lark-contact",
        domain=BusinessDomain.CONTACT,
        capabilities=("user_search", "org_lookup"),
    ),
    CliToolFamily(
        tool_name="lark-task",
        domain=BusinessDomain.TASK,
        capabilities=("task_create", "task_update", "task_list"),
    ),
    CliToolFamily(
        tool_name="lark-mail",
        domain=BusinessDomain.MAIL,
        capabilities=("mail_compose", "mail_send", "mail_search"),
    ),
)


INTENT_TO_DOMAIN: dict[IntentType, BusinessDomain] = {
    IntentType.MESSAGE_SEND: BusinessDomain.MESSAGE,
    IntentType.CALENDAR_RESCHEDULE: BusinessDomain.CALENDAR,
    IntentType.DOC_CREATE: BusinessDomain.DOC_SHEET,
    IntentType.SHEET_UPDATE: BusinessDomain.DOC_SHEET,
    IntentType.UNKNOWN: BusinessDomain.UNKNOWN,
}


INTENT_TO_CAPABILITY: dict[IntentType, CapabilityId] = {
    IntentType.MESSAGE_SEND: CapabilityId.IM_MESSAGE_SEND,
    IntentType.CALENDAR_RESCHEDULE: CapabilityId.CALENDAR_RESCHEDULE,
    IntentType.DOC_CREATE: CapabilityId.DOC_CREATE,
    IntentType.SHEET_UPDATE: CapabilityId.SHEET_UPDATE,
    IntentType.UNKNOWN: CapabilityId.UNKNOWN,
}


class LarkCliAdapter:
    """Build business-level CLI plans from normalized intents."""

    def list_tool_families(self) -> tuple[CliToolFamily, ...]:
        """Expose tool families so planning/docs stay source-of-truth."""
        return TOOL_FAMILIES

    def classify_business(self, intent: IntentType) -> BusinessDomain:
        """Map intent to business domain."""
        return INTENT_TO_DOMAIN.get(intent, BusinessDomain.UNKNOWN)

    def build_plan(self, intent: IntentType, payload: dict[str, Any]) -> CliCallPlan:
        """Backward-compatible intent-to-plan adapter."""
        return self.build_plan_for_capability(
            capability_id=INTENT_TO_CAPABILITY.get(intent, CapabilityId.UNKNOWN),
            payload=payload,
            intent=intent,
        )

    def build_plan_for_capability(
        self,
        capability_id: CapabilityId,
        payload: dict[str, Any],
        intent: IntentType = IntentType.UNKNOWN,
    ) -> CliCallPlan:
        """Create a CLI plan from a normalized capability action."""
        plan_specs = {
            CapabilityId.IM_MESSAGES_REPLY: (BusinessDomain.MESSAGE, "lark-im", "messages_reply", "message_flow_failed"),
            CapabilityId.IM_MESSAGES_SEARCH: (BusinessDomain.MESSAGE, "lark-im", "messages_search", "message_flow_failed"),
            CapabilityId.IM_CHAT_MESSAGES_LIST: (BusinessDomain.MESSAGE, "lark-im", "chat_messages_list", "message_flow_failed"),
            CapabilityId.IM_CHAT_SEARCH: (BusinessDomain.MESSAGE, "lark-im", "chat_search", "message_flow_failed"),
            CapabilityId.IM_CHAT_CREATE: (BusinessDomain.MESSAGE, "lark-im", "chat_create", "message_flow_failed"),
            CapabilityId.CALENDAR_CREATE: (BusinessDomain.CALENDAR, "lark-calendar", "event_create", "calendar_flow_failed"),
            CapabilityId.CALENDAR_AGENDA: (BusinessDomain.CALENDAR, "lark-calendar", "agenda", "calendar_flow_failed"),
            CapabilityId.CALENDAR_FREEBUSY: (BusinessDomain.CALENDAR, "lark-calendar", "freebusy", "calendar_flow_failed"),
            CapabilityId.DOC_UPDATE: (BusinessDomain.DOC_SHEET, "lark-doc", "doc_update", "doc_sheet_flow_failed"),
            CapabilityId.DOC_SEARCH: (BusinessDomain.DOC_SHEET, "lark-doc", "doc_search", "doc_sheet_flow_failed"),
            CapabilityId.SHEET_READ: (BusinessDomain.DOC_SHEET, "lark-sheets", "sheet_read", "doc_sheet_flow_failed"),
            CapabilityId.CONTACT_SEARCH: (BusinessDomain.CONTACT, "lark-contact", "contact_search", "contact_flow_failed"),
            CapabilityId.TASK_CREATE: (BusinessDomain.TASK, "lark-task", "task_create", "task_flow_failed"),
            CapabilityId.MAIL_SEND: (BusinessDomain.MAIL, "lark-mail", "mail_send", "mail_flow_failed"),
            CapabilityId.BASE_RECORD_CREATE: (BusinessDomain.DOC_SHEET, "lark-base", "record_create", "base_flow_failed"),
        }
        if capability_id == CapabilityId.IM_MESSAGE_SEND:
            return CliCallPlan(
                intent=intent,
                capability_id=capability_id,
                domain=BusinessDomain.MESSAGE,
                invocations=(
                    CliInvocation(
                        tool_family="lark-im",
                        operation="message_send",
                        arguments={
                            "chat_hint": payload.get("chat_hint", ""),
                            "chat_id": payload.get("chat_id", ""),
                            "user_id": payload.get("user_id", ""),
                            "text": payload.get("text", payload.get("message", "")),
                            "idempotency_key": payload.get("idempotency_key", ""),
                            "identity": payload.get("identity", "user"),
                        },
                    ),
                ),
                fallback_hint="message_flow_failed",
            )
        if capability_id in plan_specs:
            domain, tool_family, operation, fallback_hint = plan_specs[capability_id]
            return CliCallPlan(
                intent=intent,
                capability_id=capability_id,
                domain=domain,
                invocations=(
                    CliInvocation(
                        tool_family=tool_family,
                        operation=operation,
                        arguments=payload,
                    ),
                ),
                fallback_hint=fallback_hint,
            )
        if capability_id == CapabilityId.CALENDAR_RESCHEDULE:
            return CliCallPlan(
                intent=intent,
                capability_id=capability_id,
                domain=BusinessDomain.CALENDAR,
                invocations=(
                    CliInvocation(
                        tool_family="lark-calendar",
                        operation="event_reschedule",
                        arguments={
                            "event_hint": payload.get("event_hint", ""),
                            "target_time": payload.get("target_time", ""),
                        },
                    ),
                ),
                fallback_hint="calendar_flow_failed",
            )
        if capability_id in {CapabilityId.DOC_CREATE, CapabilityId.SHEET_UPDATE}:
            operation = "doc_create" if capability_id == CapabilityId.DOC_CREATE else "sheet_write"
            tool_family = "lark-doc" if capability_id == CapabilityId.DOC_CREATE else "lark-sheets"
            return CliCallPlan(
                intent=intent,
                capability_id=capability_id,
                domain=BusinessDomain.DOC_SHEET,
                invocations=(
                    CliInvocation(
                        tool_family=tool_family,
                        operation=operation,
                        arguments=payload,
                    ),
                ),
                fallback_hint="doc_sheet_flow_failed",
            )
        return CliCallPlan(
            intent=intent,
            capability_id=CapabilityId.UNKNOWN,
            domain=BusinessDomain.UNKNOWN,
            invocations=tuple(),
            fallback_hint="unsupported_intent_for_cli",
        )

    def build_command(
        self,
        invocation: CliInvocation,
        cli_bin: str = "lark-cli",
        dry_run: bool = False,
    ) -> list[str]:
        """Convert one invocation into a concrete lark-cli command argv."""
        if invocation.tool_family == "lark-im" and invocation.operation == "message_send":
            return self._build_im_message_send(invocation.arguments, cli_bin=cli_bin, dry_run=dry_run)
        raise ValueError(
            f"unsupported cli invocation: tool={invocation.tool_family}, operation={invocation.operation}"
        )

    @staticmethod
    def stringify_command(argv: list[str]) -> str:
        """Render command for logs/docs in Windows-compatible format."""
        return subprocess.list2cmdline(argv)

    @staticmethod
    def _build_im_message_send(arguments: dict[str, Any], cli_bin: str, dry_run: bool) -> list[str]:
        text = str(arguments.get("text", "")).strip()
        if not text:
            raise ValueError("missing message text for lark-im +messages-send")
        chat_id = str(arguments.get("chat_id", "")).strip()
        user_id = str(arguments.get("user_id", "")).strip()
        if not chat_id and not user_id:
            raise ValueError("missing chat_id/user_id for lark-im +messages-send")
        identity = str(arguments.get("identity", "user")).strip().lower() or "user"
        if identity not in {"bot", "user"}:
            raise ValueError("identity must be bot or user")
        command = [cli_bin, "im", "+messages-send", "--as", identity, "--text", text]
        if chat_id:
            command.extend(["--chat-id", chat_id])
        else:
            command.extend(["--user-id", user_id])
        idempotency_key = str(arguments.get("idempotency_key", "")).strip()
        if idempotency_key:
            command.extend(["--idempotency-key", idempotency_key])
        if dry_run:
            command.append("--dry-run")
        return command
